version: '3'
services:

  automation:
    container_name: framework
    build: .
    depends_on:
      - firefox_node
    volumes:
      - "./reports/report_dates/:/usr/app/reports/report_dates/"

  firefox_node:
    depends_on:
      - selenium-hub
    image: selenium/node-firefox
    environment:
      HUB_PORT_4444_TCP_ADDR: "selenium-hub"
      HUB_PORT_4444_TCP_PORT: 4444
    ports:
      - 4545:4444
    links:
      - selenium-hub:hub

  selenium-hub:
    container_name: selenium-hub
    image: selenium/hub
    ports:
      - 4444:4444